version: '3'

services:
  service1:
    image: service1
    container_name: service1-1
    build:
      context: .
      dockerfile: Service1/Dockerfile
    environment: 
      RABBITMQ_HOST: rabbitmq 
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    ports:
      - '8081:8080'
      
  service2:
    image: service2
    container_name: service2-1
    build:
      context: .
      dockerfile: Service2/Dockerfile
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    ports:
      - '8082:8080'
      
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq-1
    ports:
      - '5672:5672'
      - '15672:15672'
