@Service1_HostAddress = http://localhost:8081

### Post Email Change
POST {{Service1_HostAddress}}/publish/
Content-Type: application/json

{
  "FullName": "John Doe",
  "EmailAddress": "johndoe@example.com",
  "RegistrationTime": "2023-05-04T18:13:51.0Z"
}

###
